DROP TABLE A_BODEGA CASCADE CONSTRAINTS;
DROP TABLE A_ESTANTE CASCADE CONSTRAINTS;
DROP TABLE A_ALMACENAMIENTO CASCADE CONSTRAINTS;

DROP TABLE A_CLIENTEEMPRESA CASCADE CONSTRAINTS;
DROP TABLE A_CLIENTENATURAL CASCADE CONSTRAINTS;

DROP TABLE A_MENORALASUMA CASCADE CONSTRAINTS;
DROP TABLE A_PAGUEMLLEVENUNIDADES CASCADE CONSTRAINTS;
DROP TABLE A_PAGUEXLLEVEYCANTIDAD CASCADE CONSTRAINTS;
DROP TABLE A_DESCUENTOSGDOPRODUCTO CASCADE CONSTRAINTS;
DROP TABLE A_PROMOCIONPORCENTAJE CASCADE CONSTRAINTS;

DROP TABLE A_FACTURA CASCADE CONSTRAINTS;

DROP TABLE A_CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE A_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE A_PEDIDO CASCADE CONSTRAINTS;
DROP TABLE A_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE A_PROMOCION CASCADE CONSTRAINTS;
DROP TABLE A_PROVEE CASCADE CONSTRAINTS;
DROP TABLE A_PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE A_REORDEN CASCADE CONSTRAINTS;
DROP TABLE A_SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE A_TIPOPRODUCTO CASCADE CONSTRAINTS;
DROP TABLE A_VOLUMENPRODUCTO CASCADE CONSTRAINTS;
DROP TABLE A_ITEMPEDIDO CASCADE CONSTRAINTS;
DROP TABLE A_ITEMFACTURA CASCADE CONSTRAINTS;
DROP TABLE A_CARRITO CASCADE CONSTRAINTS;
DROP TABLE A_ITEMCARRITO CASCADE CONSTRAINTS;

DROP SEQUENCE SUPERANDES_SEQUENCE;
DROP SEQUENCE SUCURSAL_SEQUENCE;
DROP SEQUENCE tipoProducto_sequence;
DROP SEQUENCE almacenamiento_sequence;
DROP SEQUENCE pedido_sequence;
DROP SEQUENCE itempedido_sequence;
COMMIT;





--Creacion del secuenciador
create sequence superAndes_sequence;
--Crear otro secuenciador
create sequence tipoProducto_sequence;
--Crear otro secuenciador
create sequence sucursal_sequence;
--Crear otro secuenciador
create sequence almacenamiento_sequence;

create sequence pedido_sequence;

create sequence itempedido_sequence;

--Creacion de la tabla SUCURSAL
CREATE TABLE A_SUCURSAL
	(ID NUMBER,
		NOMBRE VARCHAR2(255) NOT NULL,
		DIRECCION VARCHAR2(255) NOT NULL,
		CIUDAD VARCHAR2(255) NOT NULL,
		CODIGOACCESO VARCHAR2(255),
		CONSTRAINT A_SUCURSAL_PK PRIMARY KEY(ID));

--Creacion de la tabla PEDIDO
CREATE TABLE A_PEDIDO
	(ID NUMBER,
		FECHAESPERADAENTREGA DATE NOT NULL,
		FECHAENTREGA DATE,
		PRECIOACORDADO NUMBER NOT NULL,
		ESTADOPEDIDO VARCHAR2(255) NOT NULL,
		ESTADOPRODUCTO VARCHAR2(255),
		IDSUCURSAL NUMBER NOT NULL,
		IDPROVEEDOR NUMBER NOT NULL,
		CONSTRAINT A_PEDIDO_PK PRIMARY KEY(ID));
ALTER TABLE A_PEDIDO
	ADD CONSTRAINT CK_PEDIDO_ESTADOPEDIDO
	CHECK(ESTADOPEDIDO IN ('EN_CAMINO','ENTREGADO'))
	ADD CONSTRAINT CK_PEDIDO_ESTADOPRODUCTO
	CHECK(ESTADOPRODUCTO IN ('BUENO','REGULAR','MALO'))
	ADD CONSTRAINT CK_PEDIDO_PRECIO
	CHECK(PRECIOACORDADO > 0)
ENABLE;



--Creacion de la tabla PROVEEDOR
CREATE TABLE A_PROVEEDOR
	(ID NUMBER,
		NOMBRE VARCHAR2(255) NOT NULL,
		CALIFICACION NUMBER(2,1) NOT NULL,
		NUMCALIFICACIONES NUMBER NOT NULL,
		CONSTRAINT A_PROVEEDOR_PK PRIMARY KEY(ID));
ALTER TABLE A_PROVEEDOR
	ADD CONSTRAINT CK_PROVEEDOR_CALIF
	CHECK( CALIFICACION BETWEEN 0 AND 5)
ENABLE;

--Creacion de la tabla PRODUCTO
CREATE TABLE A_PRODUCTO
	(ID VARCHAR2(255),
		NOMBRE VARCHAR2(255) NOT NULL,
		MARCA VARCHAR2(255) NOT NULL,
		PRESENTACION VARCHAR2(255) NOT NULL,
		CANTIDAD NUMBER NOT NULL,
		UNIDADMEDIDA VARCHAR2(255) NOT NULL,
		PRECIOUNIDADMEDIDA NUMBER NOT NULL,
		ESPECIFICACIONEMPAQUE NUMBER NOT NULL,
		EXCLUSIVO NUMBER NOT NULL,
		IDTIPOPRODUCTO NUMBER NOT NULL,
		IDCATEGORIA NUMBER NOT NULL,
		CONSTRAINT A_PRODUCTO_PK PRIMARY KEY(ID));
ALTER TABLE A_PRODUCTO
	ADD CONSTRAINT CK_PRODUCTO_CANTIDAD
	CHECK(CANTIDAD> 0)
	ADD CONSTRAINT CK_PRODUCTO_PRECIOUNIMEDIDA
	CHECK(PRECIOUNIDADMEDIDA  > 0)
	ADD CONSTRAINT CK_PRODUCTO_ESPECIFICACIONEMP
	CHECK(ESPECIFICACIONEMPAQUE > 0)
	ADD CONSTRAINT CK_PRODUCTO_UNMEDIDA
	CHECK(UNIDADMEDIDA IN ('gr','ml'))
	ADD CONSTRAINT CK_PRODUCTO_EXCL
	CHECK( EXCLUSIVO IN (1,0))
ENABLE;

--Creacion de la tabla ITEMPEDIDO
CREATE TABLE A_ITEMPEDIDO
	(ID NUMBER,
		CANTIDAD NUMBER,
		FECHAVENCIMIENTO DATE,
		IDPEDIDO NUMBER,
		IDPRODUCTO VARCHAR2(255) NOT NULL,
		PRECIOVENTA NUMBER,
		CONSTRAINT A_ITEMPEDIDO_PK PRIMARY KEY(ID));
ALTER TABLE A_ITEMPEDIDO
	ADD CONSTRAINT fk_pedido
	FOREIGN KEY (IDPEDIDO)
	REFERENCES A_PEDIDO(ID)
ENABLE;
ALTER TABLE A_ITEMPEDIDO
	ADD CONSTRAINT fk_produc
	FOREIGN KEY (IDPRODUCTO)
	REFERENCES A_PRODUCTO(ID)
ENABLE;

--Creacion de la tabla REORDEN
CREATE TABLE A_REORDEN
	(ID NUMBER,
		NIVELREORDEN NUMBER NOT NULL,
		IDSUCURSAL NUMBER NOT NULL,
		IDPRODUCTO VARCHAR2(255) NOT NULL,
		CONSTRAINT A_REORDEN_PK PRIMARY KEY(ID));
ALTER TABLE A_REORDEN
	ADD CONSTRAINT CK_REORDEN_NIVEL
	CHECK( NIVELREORDEN >0)
ENABLE;

--Creacion de la tabla VOLUMENPRODUCTO
CREATE TABLE A_VOLUMENPRODUCTO
	(ID NUMBER,
		CANTIDAD NUMBER NOT NULL,
		PESO NUMBER NOT NULL,
		VOLUMEN NUMBER NOT NULL,
		IDPRODUCTO VARCHAR2(255) NOT NULL,
		IDITEMPEDIDO NUMBER NOT NULL,
		CONSTRAINT A_VOLUMENPRODUCTO_PK PRIMARY KEY(ID));
ALTER TABLE A_VOLUMENPRODUCTO
	ADD CONSTRAINT CK_VOLUMENPRODUCTO_CANTIDAD
	CHECK(CANTIDAD > 0)
	ADD CONSTRAINT CK_VOLUMENPRODUCTO_PESO
	CHECK( PESO > 0)
	ADD CONSTRAINT CK_VOLUMENPRODUCTO_VOLUMEN
	CHECK( VOLUMEN > 0)
ENABLE;

--Creacion de la tabla ALMACENAMIENTO
CREATE TABLE A_ALMACENAMIENTO
	(ID NUMBER,
		CANTIDADMAX NUMBER NOT NULL,
		PESOMAX NUMBER NOT NULL,
		VOLUMENMAX NUMBER NOT NULL,
		IDSUCURSAL NUMBER NOT NULL,
		IDTIPOPRODUCTO NUMBER NOT NULL,
		IDVOLUMENPRODUCTO NUMBER NOT NULL,
		CONSTRAINT A_ALMACENAMIENTO_PK PRIMARY KEY(ID));
ALTER TABLE A_ALMACENAMIENTO
	ADD CONSTRAINT CK_ALMACENAMIENTO_CANTIDADMAX
	CHECK(CANTIDADMAX > 0)
	ADD CONSTRAINT CK_ALMACENAMIENTO_PESOMAX
	CHECK( PESOMAX > 0)
	ADD CONSTRAINT CK_ALMACENAMIENTO_VOLUMENMAX
	CHECK( VOLUMENMAX > 0)
ENABLE;

--Creacion de la tabla BODEGA
CREATE TABLE A_BODEGA
	(IDALMACENAMIENTO NUMBER,
		DIRECCION VARCHAR2(255) NOT NULL,
		CONSTRAINT A_BODEGA_PK PRIMARY KEY(IDALMACENAMIENTO));
ALTER TABLE A_BODEGA

	ADD CONSTRAINT fk_almacenamiento_B
	FOREIGN KEY (IDALMACENAMIENTO)

	REFERENCES A_ALMACENAMIENTO(ID)

ENABLE;

--Creacion de la tabla ESTANTE
CREATE TABLE A_ESTANTE
	(IDALMACENAMIENTO NUMBER,
		NIVELABASTECIMIENTO NUMBER NOT NULL,
		CONSTRAINT A_ESTANTE_PK PRIMARY KEY(IDALMACENAMIENTO));
ALTER TABLE A_ESTANTE

	ADD CONSTRAINT fk_almacenamiento_E
	FOREIGN KEY (IDALMACENAMIENTO)
	REFERENCES A_ALMACENAMIENTO(ID)
ENABLE;
ALTER TABLE A_ESTANTE
	ADD CONSTRAINT CK_ESTANTE_NIVEL
	CHECK(NIVELABASTECIMIENTO > 0)
ENABLE;

--Creacion de la tabla CATEGORIA
CREATE TABLE A_CATEGORIA
	(ID NUMBER,
		NOMBRE VARCHAR2(255) NOT NULL UNIQUE,
		CONSTRAINT A_CATEGORIA_PK PRIMARY KEY(ID));
ALTER TABLE A_CATEGORIA
	ADD CONSTRAINT CK_CATEGORIA_TIPO
	CHECK(NOMBRE IN ('PERECEDEROS','NO_PERECEDEROS','ASEO','ABARROTES',
			'CONGELADOS', 'PRENDA_DE_VESTIR','MUEBLES','HERRAMIENTAS',
			'ELECTRODOMESTICOS'))
ENABLE;

--Creacion de la tabla TIPOPRODUCTO
CREATE TABLE A_TIPOPRODUCTO
	(ID NUMBER,
		NOMBRE VARCHAR2(255) NOT NULL UNIQUE,
		IDCATEGORIA NUMBER NOT NULL,
		CONSTRAINT A_TIPOPRODUCTO_PK PRIMARY KEY(ID));
ALTER TABLE A_TIPOPRODUCTO
	ADD CONSTRAINT fk_categoria
	FOREIGN KEY (IDCATEGORIA)
	REFERENCES A_CATEGORIA(ID)
ENABLE;

--Creacion de la tabla PROMOCION
CREATE TABLE A_PROMOCION
	(ID NUMBER,
		FECHAEXPIRACION DATE NOT NULL,
		IDSUCURSAL NUMBER NOT NULL,
		IDPRODUCTO VARCHAR2(255) NOT NULL,
		CONSTRAINT A_PROMOCION_PK PRIMARY KEY(ID));
ALTER TABLE A_PROMOCION
	ADD CONSTRAINT fk_sucursal
	FOREIGN KEY (IDSUCURSAL)
	REFERENCES A_SUCURSAL(ID)
ENABLE;
ALTER TABLE A_PROMOCION
	ADD CONSTRAINT fk_producto
	FOREIGN KEY (IDPRODUCTO)
	REFERENCES A_PRODUCTO(ID)
ENABLE;

--Creacion de la tabla PAGUEMLLEVENUNIDADES
CREATE TABLE A_PAGUEMLLEVENUNIDADES
	(IDPROMOCION NUMBER,
		M NUMBER NOT NULL,
		N NUMBER NOT NULL,
		CONSTRAINT A_PAGUEMLLEVENUNIDADES_PK PRIMARY KEY(IDPROMOCION));
ALTER TABLE A_PAGUEMLLEVENUNIDADES
	ADD CONSTRAINT fk_promocion_MYN
	FOREIGN KEY (IDPROMOCION)
	REFERENCES A_PROMOCION(ID)
ENABLE;
ALTER TABLE A_PAGUEMLLEVENUNIDADES
	ADD CONSTRAINT CK_PAGUEMLLEVENUNIDADES_M
	CHECK(M > 0)
	ADD CONSTRAINT CK_PAGUEMLLEVENUNIDADES_N
	CHECK(N > 0)
ENABLE;

--Creacion de la tabla PAGUEXLLEVEYCANTIDAD
CREATE TABLE A_PAGUEXLLEVEYCANTIDAD
	(IDPROMOCION NUMBER,
		X NUMBER NOT NULL,
		Y NUMBER NOT NULL,
		CONSTRAINT A_PAGUEXLLEVEYCANTIDAD_PK PRIMARY KEY(IDPROMOCION));
ALTER TABLE A_PAGUEXLLEVEYCANTIDAD
	ADD CONSTRAINT fk_promocion_XY
	FOREIGN KEY (IDPROMOCION)
	REFERENCES A_PROMOCION(ID)
ENABLE;
ALTER TABLE A_PAGUEXLLEVEYCANTIDAD
	ADD CONSTRAINT CK_PAGUEMLLEVENUNIDADES_X
	CHECK(X > 0)
	ADD CONSTRAINT CK_PAGUEMLLEVENUNIDADES_Y
	CHECK(Y > 0)
ENABLE;

--Creacion de la tabla PROMOCIONPORCENTAJE
CREATE TABLE A_PROMOCIONPORCENTAJE
	(IDPROMOCION NUMBER,
	DESCUENTO NUMBER NOT NULL,
	CONSTRAINT A_PROMOCIONPORCENTAJE_PK PRIMARY KEY(IDPROMOCION));
ALTER TABLE A_PROMOCIONPORCENTAJE
	ADD CONSTRAINT fk_promocion_PP
	FOREIGN KEY (IDPROMOCION)
	REFERENCES A_PROMOCION(ID)
ENABLE;
ALTER TABLE A_PROMOCIONPORCENTAJE
	ADD CONSTRAINT CK_PROMOCIONPORCENTAJE_DESC
	CHECK(DESCUENTO > 0)
ENABLE;

--Creacion de la tabla DESCUENTOSGDOPRODUCTO
CREATE TABLE A_DESCUENTOSGDOPRODUCTO
	(IDPROMOCION NUMBER,
	DESCUENTO NUMBER NOT NULL,
	CONSTRAINT A_DESCUENTOSGDOPRODUCTO_PK PRIMARY KEY(IDPROMOCION));
ALTER TABLE A_DESCUENTOSGDOPRODUCTO
	ADD CONSTRAINT fk_promocion_DSGDO
	FOREIGN KEY (IDPROMOCION)
	REFERENCES A_PROMOCION(ID)
ENABLE;
ALTER TABLE A_DESCUENTOSGDOPRODUCTO
	ADD CONSTRAINT CK_DESCUENTOSGDOPRODUCTO_DESC
	CHECK(DESCUENTO > 0)
ENABLE;

--Creacion de la tabla MENORALASUMA
CREATE TABLE A_MENORALASUMA
	(IDPROMOCION NUMBER,
	CONSTRAINT A_MENORALASUMA_PK PRIMARY KEY(IDPROMOCION));
ALTER TABLE A_MENORALASUMA
	ADD CONSTRAINT fk_promocion_MS
	FOREIGN KEY (IDPROMOCION)
	REFERENCES A_PROMOCION(ID)
ENABLE;

--Creacion de la tabla CLIENTE
CREATE TABLE A_CLIENTE
	(ID NUMBER,
		PASSWORD VARCHAR2(255) NOT NULL,
		NOMBRE VARCHAR2(255) NOT NULL,
		CORREO VARCHAR2(255) NOT NULL,
		CONSTRAINT A_CLIENTE_PK PRIMARY KEY(ID));
ALTER TABLE A_CLIENTE
	ADD CONSTRAINT CK_CLIENTE_CORREO
	CHECK(regexp_like(CORREO, '[[:alnum:]]+@[[:alnum:]]+\.[[:alnum:]]'))
ENABLE;

--Creacion de la tabla CLIENTEEMPRESA
CREATE TABLE A_CLIENTEEMPRESA
	(IDCLIENTE NUMBER,
	DIRECCION VARCHAR2(255),
	CONSTRAINT A_CLIENTEEMPRESA_PK PRIMARY KEY(IDCLIENTE));
ALTER TABLE A_CLIENTEEMPRESA
	ADD CONSTRAINT fk_cliente_E
	FOREIGN KEY (IDCLIENTE)
	REFERENCES A_CLIENTE(ID)
ENABLE;

--Creacion de la tabla CLIENTENATURAL
CREATE TABLE A_CLIENTENATURAL
	(IDCLIENTE NUMBER,
	CONSTRAINT A_CLIENTENATURAL_PK PRIMARY KEY(IDCLIENTE));
ALTER TABLE A_CLIENTENATURAL
	ADD CONSTRAINT fk_cliente_N
	FOREIGN KEY (IDCLIENTE)
	REFERENCES A_CLIENTE(ID)
ENABLE;

--Creacion de la tabla FACTURA
CREATE TABLE A_FACTURA
	(ID NUMBER,
		FECHA DATE NOT NULL,
		IDSUCURSAL NUMBER NOT NULL,
		IDCLIENTE NUMBER NOT NULL,
		CONSTRAINT A_FACTURA_PK PRIMARY KEY(ID));
ALTER TABLE A_FACTURA
	ADD CONSTRAINT fk_cliente
	FOREIGN KEY (IDCLIENTE)
	REFERENCES A_CLIENTE(ID)
ENABLE;
ALTER TABLE A_FACTURA
	ADD CONSTRAINT fk_sucursal_F
	FOREIGN KEY (IDSUCURSAL)
	REFERENCES A_SUCURSAL(ID)
ENABLE;

--Creacion de la tabla ITEMFACTURA
CREATE TABLE A_ITEMFACTURA
(ID NUMBER,
	CANTIDAD NUMBER,
	IDFACTURA NUMBER NOT NULL,
	IDPRODUCTO VARCHAR(255),
	PRECIO NUMBER NOT NULL,
	CONSTRAINT A_ITEMFACTURA_PK PRIMARY KEY(ID));
ALTER TABLE A_ITEMFACTURA
	ADD CONSTRAINT fk_factura
	FOREIGN KEY (IDPRODUCTO)
	REFERENCES A_PRODUCTO(ID)
ENABLE;
ALTER TABLE A_ITEMFACTURA
	ADD CONSTRAINT fk_producto_i
	FOREIGN KEY (IDFACTURA)
	REFERENCES A_FACTURA(ID)
ENABLE;

--Creacion de la tabla PROVEE
CREATE TABLE A_PROVEE
	(IDPROVEEDOR NUMBER,
		IDPRODUCTO VARCHAR2(255),
		PRECIOCOMPRA NUMBER,
		PRECIOVENTA NUMBER,
		CONSTRAINT A_PROVEE_PK PRIMARY KEY(IDPROVEEDOR,IDPRODUCTO));
ALTER TABLE A_PROVEE
	ADD CONSTRAINT fk_proveedor_p
	FOREIGN KEY (IDPROVEEDOR)
	REFERENCES A_PROVEEDOR(ID)
ENABLE;
ALTER TABLE A_PROVEE
	ADD CONSTRAINT fk_producto_p
	FOREIGN KEY (IDPRODUCTO)
	REFERENCES A_PRODUCTO(ID)
ENABLE;

--Creacion de la tabla CARRITO
CREATE TABLE A_CARRITO
(ID NUMBER,
	IDSUCURSAL NUMBER,
	IDCLIENTE NUMBER UNIQUE,
	ESTADO VARCHAR(255),
	CONSTRAINT A_CARRITO_PK PRIMARY KEY (ID));
ALTER TABLE A_CARRITO
	ADD CONSTRAINT fk_sucursal_c
	FOREIGN KEY (IDSUCURSAL)
	REFERENCES A_SUCURSAL(ID)
ENABLE;
ALTER TABLE A_CARRITO
	ADD CONSTRAINT fk_cliente_c
	FOREIGN KEY (IDCLIENTE)
	REFERENCES A_CLIENTE(ID)
ENABLE;
ALTER TABLE A_CARRITO
	ADD CONSTRAINT CK_CARRITO_ESTADO
	CHECK( ESTADO IN ('EN_USO'))
ENABLE;

--Creacion de la tabla ITEMCARRITO
CREATE TABLE A_ITEMCARRITO
	(ID NUMBER,
		IDCARRITO NUMBER,
		IDPRODUCTO VARCHAR(255),
		CANTIDAD NUMBER,
		IDESTANTE NUMBER,
		CONSTRAINT A_ITEMCARRITO_PK PRIMARY KEY (ID));
ALTER TABLE A_ITEMCARRITO
	ADD CONSTRAINT fk_carrito
	FOREIGN KEY (IDCARRITO)
	REFERENCES A_CARRITO(ID)
ENABLE;
ALTER TABLE A_ITEMCARRITO
	ADD CONSTRAINT fk_producto_c
	FOREIGN KEY (IDPRODUCTO)
	REFERENCES A_PRODUCTO(ID)
ENABLE;
ALTER TABLE A_ITEMCARRITO
	ADD CONSTRAINT fk_estante
	FOREIGN KEY (IDESTANTE)
	REFERENCES A_ESTANTE(IDALMACENAMIENTO)
ENABLE;

--Llaves foraneas de la tabla pedido
ALTER TABLE A_PEDIDO
	ADD CONSTRAINT fk_sucursal_ped
	FOREIGN KEY (IDSUCURSAL)
	REFERENCES A_SUCURSAL(ID)
ENABLE;
ALTER TABLE A_PEDIDO
	ADD CONSTRAINT fk_proveedor_ped
	FOREIGN KEY (IDPROVEEDOR)
	REFERENCES A_PROVEEDOR(ID)
ENABLE;

--Llaves foraneas de la tabla producto
ALTER TABLE A_PRODUCTO
	ADD CONSTRAINT fk_tipoProducto_prod
	FOREIGN KEY (IDTIPOPRODUCTO)
	REFERENCES A_TIPOPRODUCTO(ID)
ENABLE;
ALTER TABLE A_PRODUCTO
	ADD CONSTRAINT fk_categoria_prod
	FOREIGN KEY (IDCATEGORIA)
	REFERENCES A_CATEGORIA(ID)
ENABLE;


--Llaves foraneas de la tabla reorden
ALTER TABLE A_REORDEN
	ADD CONSTRAINT fk_sucursal_r
	FOREIGN KEY (IDSUCURSAL)
	REFERENCES A_SUCURSAL(ID)
ENABLE;
ALTER TABLE A_REORDEN
	ADD CONSTRAINT fk_producto_r
	FOREIGN KEY (IDPRODUCTO)
	REFERENCES A_PRODUCTO(ID)
ENABLE;

--Llaves foraneas de la tabla volumenProducto
ALTER TABLE A_VOLUMENPRODUCTO
	ADD CONSTRAINT fk_producto_vol
	FOREIGN KEY (IDPRODUCTO)
	REFERENCES A_PRODUCTO(ID)
ENABLE;
ALTER TABLE A_VOLUMENPRODUCTO
	ADD CONSTRAINT fk_itempedido_vol
	FOREIGN KEY (IDITEMPEDIDO)
	REFERENCES A_ITEMPEDIDO(ID)
ENABLE;

--Llaves foraneas de la tabla almacenamiento
ALTER TABLE A_ALMACENAMIENTO
	ADD CONSTRAINT fk_sucursal_alm
	FOREIGN KEY (IDSUCURSAL)
	REFERENCES A_SUCURSAL(ID)
ENABLE;
ALTER TABLE A_ALMACENAMIENTO
	ADD CONSTRAINT fk_volumenProducto_alm
	FOREIGN KEY (IDVOLUMENPRODUCTO)
	REFERENCES A_VOLUMENPRODUCTO(ID)
ENABLE;
ALTER TABLE A_ALMACENAMIENTO
	ADD CONSTRAINT fk_tipoProducto_alm
	FOREIGN KEY (IDTIPOPRODUCTO)
	REFERENCES A_TIPOPRODUCTO(ID)
ENABLE;

COMMIT;



--RF1 REGISTRAR PROVEEDORES
-- Insertar varios proveedores sin ningun error

INSERT INTO A_PROVEEDOR (ID,NOMBRE,CALIFICACION,NUMCALIFICACIONES) VALUES(12354789, 'PROVEEDOR1',1,1);
INSERT INTO A_PROVEEDOR (ID,NOMBRE,CALIFICACION,NUMCALIFICACIONES) VALUES(15478665, 'PROVEEDOR2',1,1);
INSERT INTO A_PROVEEDOR (ID,NOMBRE,CALIFICACION,NUMCALIFICACIONES) VALUES(158796, 'PROVEEDOR3',1,1);
INSERT INTO A_PROVEEDOR (ID,NOMBRE,CALIFICACION,NUMCALIFICACIONES) VALUES(147896, 'PROVEEDOR4',1,1);

--Insertar un proveedor sin NOMBRE
--INSERT INTO A_PROVEEDOR (ID,NOMBRE,CALIFICACION,NUMCALIFICACIONES) VALUES((15417451),NULL,1,1);
-- Insertar un proveedor con una CALIFICACION fuera del rango
--INSERT INTO A_PROVEEDOR (ID,NOMBRE,CALIFICACION,NUMCALIFICACIONES) VALUES((159865), 'PROVEEDOR7',-1,1);
--INSERT INTO A_PROVEEDOR (ID,NOMBRE,CALIFICACION,NUMCALIFICACIONES) VALUES((9874563), 'PROVEEDOR8',9,1);


--RF2 REGISTRAR PRODUCTOS
--Insertar varios productos sin singun error

  --Crear la categoria a la que va a pertenecer el producto
  INSERT INTO A_CATEGORIA (ID, NOMBRE) VALUES ((SUPERANDES_SEQUENCE.nextval),'CONGELADOS');
      --Crear el tipo del producto
      INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(( tipoProducto_sequence.nextval ), 'Carnes',( SUPERANDES_SEQUENCE.currval ));
          --Crear el producto
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA,PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( ('14586'   ),'Carne molida','Vacuno','Empaque plastico',1000,'gr',7.12,0.2,0,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
          INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Pollo',(SUPERANDES_SEQUENCE.currval));
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( (  '15986' ),'Pechuga','pimpollo','Empaque plastico',1000,'gr',8.68,0.2,0,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
          INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Pescado',(SUPERANDES_SEQUENCE.currval));
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( ( '15573'  ),'Filete de tilapia','Fisher boy','Empaque plastico',1000,'gr',9.84,0.2,0,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
          INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Pasabocas',(SUPERANDES_SEQUENCE.currval));
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( ('25987'   ),'Empanadas de carne','Zenu','Empaque plastico',2500,'gr',8.2,0.2,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));

  --Crear la categoria a la que va a pertenecer el producto
  INSERT INTO A_CATEGORIA (ID, NOMBRE) VALUES ((SUPERANDES_SEQUENCE.nextval),'ELECTRODOMESTICOS');
      --Crear el tipo del producto
      INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(( tipoProducto_sequence.nextval ), 'Nevera',( SUPERANDES_SEQUENCE.currval ));
          --Crear el producto
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA,PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( ( '5215'),'Nevera 3242LG','LG','Caja',132900,'gr',1000,10.4,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
          INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Microondas',(SUPERANDES_SEQUENCE.currval));
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( ( '25893'  ),'Horno microondas Samsung','Samsung','Caja',8000,'gr',9.68,8.7,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
          INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Televisor',(SUPERANDES_SEQUENCE.currval));
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( ('258745'   ),'Televisor LED LG','LG','Caja',10000,'gr',15.3,8.7,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
          INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Lavadora',(SUPERANDES_SEQUENCE.currval));
          INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
          VALUES( ( '32569'  ),'Lavadora Haceb','Haceb','Caja',78750,'gr',9.2,10.6,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));

      --Crear la categoria a la que va a pertenecer el producto
      INSERT INTO A_CATEGORIA (ID, NOMBRE) VALUES ((SUPERANDES_SEQUENCE.nextval),'PERECEDEROS');

          --Crear el tipo del producto
          INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(( tipoProducto_sequence.nextval ), 'Galletas',( SUPERANDES_SEQUENCE.currval ));
              --Crear el producto
              INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
              VALUES( ('12365'   ),'Galletas festival','Festival','Empaque plastico',900,'gr',3.84,0.2,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
              INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Enlatados',(SUPERANDES_SEQUENCE.currval));
              INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
              VALUES( (  '44475' ),'Atun Margarita','Margarita','Lata',800,'gr',2.84,0.5,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
              INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Bebidas',(SUPERANDES_SEQUENCE.currval));
              INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
              VALUES( (  '14851' ),'Jugo hit','HIT','Botella plastica',2500,'ml',5.2,0.2,1,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));
              INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(tipoProducto_sequence.nextval, 'Lacteos',(SUPERANDES_SEQUENCE.currval));
              INSERT INTO A_PRODUCTO (ID,NOMBRE,MARCA, PRESENTACION,CANTIDAD,UNIDADMEDIDA,PRECIOUNIDADMEDIDA,ESPECIFICACIONEMPAQUE,EXCLUSIVO,IDTIPOPRODUCTO,IDCATEGORIA)
              VALUES( ( '15452'   ),'Leche alqueria','Alqueria','Bolsa',1000,'ml',4.68,0.2,1
              ,( tipoProducto_sequence.currval ),( SUPERANDES_SEQUENCE.currval ));


  -- Crear un categoria Repetida
  --INSERT INTO A_CATEGORIA (ID, NOMBRE) VALUES ((SUPERANDES_SEQUENCE.nextval),'ELECTRODOMESTICOS');
  --Crear un tipo de producto repetido
  --INSERT INTO A_TIPOPRODUCTO(ID, NOMBRE, IDCATEGORIA) VALUES(( 14785236 ), 'Nevera',( SUPERANDES_SEQUENCE.currval ));


--RF3 REGISTRAR CLIENTES
  --Registrar CLIENTES
  INSERT INTO A_CLIENTE (ID,PASSWORD,NOMBRE,CORREO) VALUES( 1018513457, '1018513457', 'Diany Yisel Quintero Perozo','dy.quintero@uniandes.edu.co');
  INSERT INTO A_CLIENTE (ID,PASSWORD,NOMBRE,CORREO) VALUES( 1004232331,'1004232331','Juan Ortega Riveros','ja.ortega@uniandes.edu.co');
  INSERT INTO A_CLIENTE (ID,PASSWORD,NOMBRE,CORREO) VALUES( 89541579,'89541579','Tienda San Isidro','tiendaSanIsidro@gmail.com');
  INSERT INTO A_CLIENTE (ID,PASSWORD,NOMBRE,CORREO) VALUES( 96578582,'96578582','Restaurante Villa Vieja','restauranteVillaVieja@gmail.com');

  --Registrar cliente con un correo invalido
  --INSERT INTO A_CLIENTE (ID,NOMBRE,CORREO) VALUES( 1018513457, 'Diany Yisel Quintero Perozo','dy.quinterouniandes.edu.co');

  --Registrar clientes naturales
  INSERT INTO A_CLIENTENATURAL (IDCLIENTE) VALUES(1018513457);
  INSERT INTO A_CLIENTENATURAL (IDCLIENTE) VALUES(1004232331);

  --Registrar clientes empresa
  INSERT INTO A_CLIENTEEMPRESA (IDCLIENTE,DIRECCION) VALUES (89541579,'calle 37 sur # 8-36 San Isidro');
  INSERT INTO A_CLIENTEEMPRESA (IDCLIENTE,DIRECCION) VALUES (96578582,'carrera 3 # 22-11 apto 201 Germania');

  --RF4 REGISTRAR UNA SUCURSAL
    --Registrar varias sucursales sin ningun error

    INSERT INTO A_SUCURSAL(ID, NOMBRE, DIRECCION,CIUDAD, CODIGOACCESO) VALUES ((SUCURSAL_SEQUENCE.nextval), 'EXITO 20 DE JULIO', 'Cl. 20 Sur 20 de Julio','Bogotá', '123');
    INSERT INTO A_SUCURSAL(ID, NOMBRE, DIRECCION,CIUDAD, CODIGOACCESO) VALUES ((SUCURSAL_SEQUENCE.nextval), 'EXITO LAS NIEVES', 'Cra. 7 #22 - 36 las nieves','Bogotá', '123');
    INSERT INTO A_SUCURSAL(ID, NOMBRE, DIRECCION,CIUDAD, CODIGOACCESO) VALUES ((SUCURSAL_SEQUENCE.nextval), 'EXITO CHAPINERO', 'Cl. 52 #13-70 Chapinero','Bogotá', '123');
    INSERT INTO A_SUCURSAL(ID, NOMBRE, DIRECCION,CIUDAD, CODIGOACCESO) VALUES ((SUCURSAL_SEQUENCE.nextval), 'EXITO FONTIBON', 'Avenida Centenario # 106-104','Bogotá', '123');
    INSERT INTO A_SUCURSAL(ID, NOMBRE, DIRECCION,CIUDAD, CODIGOACCESO) VALUES ((SUCURSAL_SEQUENCE.nextval), 'EXITO ALAMOS', 'Cra. 96 #70A - 85 Alamos','Bogotá', '123');
    INSERT INTO A_SUCURSAL(ID, NOMBRE, DIRECCION,CIUDAD, CODIGOACCESO) VALUES ((SUCURSAL_SEQUENCE.nextval), 'EXITO COLINA', 'Avenida Boyaca Carrera #72','Bogotá', '123');

    --Registrar una sucursal con un atributo NULL
    --INSERT INTO A_SUCURSAL(ID, NOMBRE, DIRECCION,CIUDAD) VALUES ((SUPERANDES_SEQUENCE.nextval), 'EXITO COLINA', NULL,'Bogotá');

  -- Registrar pedidos

  INSERT INTO A_PEDIDO (ID, FECHAESPERADAENTREGA,FECHAENTREGA,PRECIOACORDADO,ESTADOPEDIDO,IDSUCURSAL,IDPROVEEDOR) VALUES (pedido_sequence.nextval,'04-11-2018','04-11-2018',600000,'EN_CAMINO', 6, 12354789 );
  INSERT INTO A_ITEMPEDIDO (ID,	CANTIDAD,	FECHAVENCIMIENTO,	IDPEDIDO,	IDPRODUCTO,	PRECIOVENTA) VALUES (itempedido_sequence.nextval, 400, '20-11-2019', pedido_sequence.currval,'14586', 2000);

  --Crear un volumenProducto apra asignarle al almacenamiento
  INSERT INTO A_VOLUMENPRODUCTO (ID,CANTIDAD,PESO,VOLUMEN, IDPRODUCTO, IDITEMPEDIDO) VALUES( (SUPERANDES_SEQUENCE.nextval),400,800000,800000,'14586', itempedido_sequence.currval);
  --Crear un almacenamiento
  INSERT INTO A_ALMACENAMIENTO (ID,CANTIDADMAX,PESOMAX,VOLUMENMAX,IDSUCURSAL,IDTIPOPRODUCTO,IDVOLUMENPRODUCTO)
  VALUES((almacenamiento_sequence.nextval),400,1500000,1500000,(SUCURSAL_SEQUENCE.currval),(tipoProducto_sequence.currval),(SUPERANDES_SEQUENCE.currval));
  --Registrar la bodega
  INSERT INTO A_BODEGA(IDALMACENAMIENTO,DIRECCION) VALUES((almacenamiento_sequence.currval),'Cra 5 20-76 San Isidro');

--RF6 REGISTRAR UN ESTANTE A UNA SUCURSAL


  --Crear un volumenProducto apra asignarle al almacenamiento
  INSERT INTO A_VOLUMENPRODUCTO (ID,CANTIDAD,PESO,VOLUMEN, IDPRODUCTO, IDITEMPEDIDO) VALUES( (SUPERANDES_SEQUENCE.nextval), 200,80000,80000,'14586',itempedido_sequence.currval);
  --Crear un almacenamiento
  INSERT INTO A_ALMACENAMIENTO (ID,CANTIDADMAX,PESOMAX,VOLUMENMAX,IDSUCURSAL,IDTIPOPRODUCTO,IDVOLUMENPRODUCTO)
  VALUES((almacenamiento_sequence.nextval), 200,100000,100000,(SUCURSAL_SEQUENCE.currval),(tipoProducto_sequence.currval),(SUPERANDES_SEQUENCE.currval));
  --Registrar el estante
  INSERT INTO A_ESTANTE(IDALMACENAMIENTO,NIVELABASTECIMIENTO) VALUES((almacenamiento_sequence.currval),30);

  --Crear un volumenProducto apra asignarle al almacenamiento
  INSERT INTO A_VOLUMENPRODUCTO (ID,CANTIDAD,PESO,VOLUMEN, IDPRODUCTO, IDITEMPEDIDO) VALUES( (SUPERANDES_SEQUENCE.nextval), 200,80000,80000,'14586',itempedido_sequence.currval);
  --Crear un almacenamiento
  INSERT INTO A_ALMACENAMIENTO (ID,CANTIDADMAX,PESOMAX,VOLUMENMAX,IDSUCURSAL,IDTIPOPRODUCTO,IDVOLUMENPRODUCTO)
  VALUES((almacenamiento_sequence.nextval), 200,100000,100000,(SUCURSAL_SEQUENCE.currval),(tipoProducto_sequence.currval),(SUPERANDES_SEQUENCE.currval));
  --Registrar el estante
  INSERT INTO A_ESTANTE(IDALMACENAMIENTO,NIVELABASTECIMIENTO) VALUES((almacenamiento_sequence.currval),30);



  INSERT INTO A_PEDIDO (ID, FECHAESPERADAENTREGA,FECHAENTREGA,PRECIOACORDADO,ESTADOPEDIDO,IDSUCURSAL,IDPROVEEDOR) VALUES (pedido_sequence.nextval,'04-11-2018','04-11-2018',600000,'EN_CAMINO', 6, 147896 );
  INSERT INTO A_ITEMPEDIDO (ID,	CANTIDAD,	FECHAVENCIMIENTO,	IDPEDIDO,	IDPRODUCTO,	PRECIOVENTA) VALUES (itempedido_sequence.nextval, 400, '20-11-2019', pedido_sequence.currval,'15452', 2000);

  --RF5 REGISTRAR UNA BODEGA A UNA SUCURSAL

    --Crear un volumenProducto apra asignarle al almacenamiento
    INSERT INTO A_VOLUMENPRODUCTO (ID,CANTIDAD,PESO,VOLUMEN,IDPRODUCTO, IDITEMPEDIDO) VALUES( (SUPERANDES_SEQUENCE.nextval),400,800000,800000,'15452',itempedido_sequence.currval);
    --Crear un almacenamiento
    INSERT INTO A_ALMACENAMIENTO (ID,CANTIDADMAX,PESOMAX,VOLUMENMAX,IDSUCURSAL,IDTIPOPRODUCTO,IDVOLUMENPRODUCTO)
    VALUES((almacenamiento_sequence.nextval),400,1500000,1500000,(SUCURSAL_SEQUENCE.currval),(tipoProducto_sequence.currval),(SUPERANDES_SEQUENCE.currval));
    --Registrar la bodega
    INSERT INTO A_BODEGA(IDALMACENAMIENTO,DIRECCION) VALUES((almacenamiento_sequence.currval),'Cra 4 20-76 Las aguas');

    --Crear un volumenProducto apra asignarle al almacenamiento
    INSERT INTO A_VOLUMENPRODUCTO (ID,CANTIDAD,PESO,VOLUMEN, IDPRODUCTO, IDITEMPEDIDO) VALUES( (SUPERANDES_SEQUENCE.nextval), 200,80000,80000,'15452',itempedido_sequence.currval);
    --Crear un almacenamiento
    INSERT INTO A_ALMACENAMIENTO (ID,CANTIDADMAX,PESOMAX,VOLUMENMAX,IDSUCURSAL,IDTIPOPRODUCTO,IDVOLUMENPRODUCTO)
    VALUES((almacenamiento_sequence.nextval), 200,100000,100000,(SUCURSAL_SEQUENCE.currval),(tipoProducto_sequence.currval),(SUPERANDES_SEQUENCE.currval));
    --Registrar el estante
    INSERT INTO A_ESTANTE(IDALMACENAMIENTO,NIVELABASTECIMIENTO) VALUES((almacenamiento_sequence.currval),30);

    --Crear un volumenProducto apra asignarle al almacenamiento
    INSERT INTO A_VOLUMENPRODUCTO (ID,CANTIDAD,PESO,VOLUMEN, IDPRODUCTO, IDITEMPEDIDO) VALUES( (SUPERANDES_SEQUENCE.nextval), 200,80000,80000,'15452',itempedido_sequence.currval);
    --Crear un almacenamiento
    INSERT INTO A_ALMACENAMIENTO (ID,CANTIDADMAX,PESOMAX,VOLUMENMAX,IDSUCURSAL,IDTIPOPRODUCTO,IDVOLUMENPRODUCTO)
    VALUES((almacenamiento_sequence.nextval), 200,100000,100000,(SUCURSAL_SEQUENCE.currval),(tipoProducto_sequence.currval),(SUPERANDES_SEQUENCE.currval));
    --Registrar el estante
    INSERT INTO A_ESTANTE(IDALMACENAMIENTO,NIVELABASTECIMIENTO) VALUES((almacenamiento_sequence.currval),30);



  --LLenar la tabla PROVEE
  INSERT INTO A_PROVEE (IDPROVEEDOR, IDPRODUCTO, PRECIOCOMPRA, PRECIOVENTA ) VALUES(12354789,'14586',1000,2000);
  INSERT INTO A_PROVEE (IDPROVEEDOR, IDPRODUCTO, PRECIOCOMPRA, PRECIOVENTA ) VALUES(158796,'14586',1000,2000);
  INSERT INTO A_PROVEE (IDPROVEEDOR, IDPRODUCTO, PRECIOCOMPRA, PRECIOVENTA ) VALUES(147896,'15452',1000,2000);
  INSERT INTO A_PROVEE (IDPROVEEDOR, IDPRODUCTO, PRECIOCOMPRA, PRECIOVENTA ) VALUES(15478665,'15452',1000,2000);

  --LLenar la tabla REORDEN
  INSERT INTO A_REORDEN ( ID,NIVELREORDEN,IDSUCURSAL,IDPRODUCTO ) VALUES (SUPERANDES_SEQUENCE.nextval,250,6,'14586');
  INSERT INTO A_REORDEN ( ID,NIVELREORDEN,IDSUCURSAL,IDPRODUCTO ) VALUES (SUPERANDES_SEQUENCE.nextval,250,6,'15452');

COMMIT;
